server:
  port: 9401
spring:
  profiles:
    active: dev
  application:
    name: micro-oauth2-auth
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.251.121:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    database: 0
    port: 16379
    host: 192.168.251.122
    password:
management:
  endpoints:
    web:
      exposure:
        include: "*"