# 配置应用基本信息
server:
  port: 8080
spring:
  application:
    name: consumer-service
# 配置eurekaserver
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true # 默认注册时使用的是主机名，想用ip进行注册添加如下配置
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #管控台展示服务ip+port
# 配置熔断策略：
#hystrix:
#  command:
#    default:
#      circuitBreaker:
#        forceOpen: false # 强制打开熔断器 默认false关闭的
#        errorThresholdPercentage: 50 # 触发熔断错误比例阈值，默认值50%
#        sleepWindowInMilliseconds: 5000  # 熔断后休眠时长，默认值5秒
#        requestVolumeThreshold: 20  # 熔断触发最小请求次数，默认值是20
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 1000  # 熔断超时设置，默认为1秒
##暴露全部监控信息,可以只填写hystrix.stream，也可以暴露全部 * ，注意在yml文件中特殊符号需要加引号
#management.endpoints.web.exposure.include: '*'
#
## 配置熔断器超时时间
#ribbon:
#  ConnectTimeout: 2000  # 连接超时时长
#  ReadTimeout: 5000  # 读取数据超时时长
#  MaxAutoRetries: 0  # 当前服务器的重试次数【针对请求】
#  MaxAutoRetriesNextServer: 0  # 重试多少次服务【针对服务】
#  OkToRetryOnAllOperations: false  # 是否对所有的请求方式都重试
#
#feign:
#  hystrix.enabled: true # 开启Feign的熔断功能
#  compression:
#    request:
#      enabled: true # 开启请求压缩
#      mime-types: text/html,application/xml,application/json  # 设置压缩的数据类型
#      min-request-size: 2048  # 设置触发压缩的大小下限
#    response.enabled: true # 开启响应压缩
#
## com.sjc 包下的日志级别都为Debug
#logging.level:
#  com.sjc: debug