# 端口
server.port: 12000
# 应用名称
spring:
  application.name: config-server
  rabbitmq: # RabbitMQ的服务地址
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  # git仓库地址
  cloud.config.server.git.uri: https://gitee.com/sangjiacun/sjc-spring-cloud-config.git
# 注册中心地址
eureka.client.service-url.defaultZone: http://eureka1:8761/eureka,http://eureka2:8762/eureka

# 触发配置文件广播的地址actuator的endpoint
management.endpoints.web.exposure.include: bus-refresh


